// src/constants/serviciosPDT.js
// Lista de 28 servicios PDT

export const SERVICIOS_PDT = [
  'BANDA ANCHA FTTX',
  'CXAAS CLOUD',
  'DEDICADO TELMEX',
  'EMPRESARIAL TELMEX',
  'EXTRANET DOMESTIC',
  'EXTRANET LOCAL',
  'INTERNET SEGURO CORPORATIVO',
  'INTERNET SEGURO',
  'INTRANET DOMESTIC',
  'INTRANET LOCAL',
  'LANWLAN ADMINISTRADA',
  'MPLS EXTRA DOMESTIC',
  'MPLS INTRA DOMESTIC',
  'MPLS INTRA LOCAL',
  'MPLS TRANSACCIONAL',
  'MPLS EXTRA LOCAL',
  'NOVEDAD CAMBIO DE ACCESO',
  'NOVEDAD CAMBIO DE EQUIPO',
  'PAQUETE HOSTING',
  'PBX ADMINISTRADA TELMEX',
  'PBX ADMINISTRADA',
  'PBX CLARO CLOUD WEBEX',
  'PL ETHERNET',
  'PRIVATE LINE SERVICES',
  'SDWAN CLARO',
  'SOLUCIONES 3G',
  'SOLUCIONES ADMINISTRADAS',
  'TEL. OFICINA'
];